# Generated by Django 4.2.15 on 2024-09-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='done',
            new_name='completed',
        ),
    ]
